### PR TITLE
Added missing content type header in create and mkdir methods

### PR DESCRIPTION
**Pull request by zonia3000**
Hi,
the methods `create` and `mkdir` aren't providing the Content-Type header. Our VOSpace implementation accepts both XML and JSON (custom, non-standard), so we need the header properly set to perform the content negotiation.

Cheers,
Sonia

### CODE REVIEW

**Comment by andamian** [comment]
@zonia3000 apologies for the delays - I didn't forget about this. The CI is currently broken and we are trying to fix it before we can merge new code.

**Comment by zonia3000** [comment]
Hi @andamian, no problem! Thanks for keeping me informed!

**Comment by andamian** [comment]
@zonia3000 - CI is now working but this PR is still failing for some reason. Can you pull master into your branch and push it again, please?

**Comment by zonia3000** [comment]
Hi, I couldn't pull (it was already updated), so I moved my commit after yours and I made a force push. Let's see if it works.

**Comment by andamian** [comment]
@zonia3000 - Now it's failing because the unit tests have not been updated to reflect your changes. If you are familiar with `tox` and have it installed you could run these tests from it. Otherwise, on your local environment run `pytest vos` (do not forget to install the testing environment `pip install -r vos/dev_requirements.txt`. The entire dev process is documented here: https://github.com/opencadc/vostools/tree/master/vos#development. Please let me know if you have questions.

**Comment by andamian** [comment]
@zonia3000 - The new release of `vos (3.3.2)` incorporates this fix if you want to start using it. Thanks again for your contribution.

**Comment by zonia3000** [comment]
Thank you!

**Pull request merged**
